name: dart_dasar_05_application
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
publish_to: none
dependencies:
  dart_dasar_04_library:
    git:
      url: https://github.com/AlfonsInfo/dart-library.git 
      ref: 1.0.0 # branch or tag

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
