name: dart_dasar_04_library
description: Learning creating packages / library
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

# Dependency for development only
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
